all:
	@pushd vmware_physical_tsc & nmake /nologo & popd
	@pushd sync_vmware_host_tsc & nmake /nologo & popd

clean:
	@pushd vmware_physical_tsc & nmake /nologo clean & popd
	@pushd sync_vmware_host_tsc & nmake /nologo clean & popd
