#ifndef __SHIELD_IOCTL_H__
#define __SHIELD_IOCTL_H__

#define IOCTL_SHIELD_TYPE 0xB080

#define IOCTL_SHIELD_START_PROTECTION \
    CTL_CODE( IOCTL_SHIELD_TYPE, 0x0A00, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS  )

#define IOCTL_SHIELD_STOP_PROTECTION \
    CTL_CODE( IOCTL_SHIELD_TYPE, 0x0A01, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS  )

#define DS_WINNT_DEVICE_NAME L"\\Device\\DeepShield"
#define DS_MSDOS_DEVICE_NAME L"\\DosDevices\\DeepShield"

#endif
